server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: "spring"
            client-id: "client"
            client-secret: "{noop}secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "openid"
              - "user.read"
        provider:
          spring:
            issuer-uri: "http://localhost:9000"
  cloud:
    gateway:
      routes:
        - id: products-route
          uri: ${PRODUCTS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/products
          filters:
            - SetPath=/api/v1/products
            - TokenRelay=
logging:
  level:
    '[org.springframework.security]': TRACE
