server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: products-route
          uri: ${PRODUCTS_SERVICE_URL:http://localhost:8082/api/v1/products}
          predicates:
            - Path=/products
  application:
    name: product-service
  profiles:
    active: default
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true
